---
title: "linear"
author: "Ben"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Linear models

```{r fake}
# Generate some fake data
dat1 <- data.frame(group = "A",
                   x = 1:10,
                   y = 1:10 + rnorm(10))
dat2 <- data.frame(group = "B",
                   x = 1:10,
                   y = 1:10 * 2 + rnorm(10) - 3)

dat <- rbind(dat1, dat2)

library(ggplot2)
ggplot(dat, aes(x, y, color = group)) + geom_point()
```

## Simplest model (no groups)

```{r m1}
m1 <- lm(y ~ x, data = dat)
summary(m1)

dat$m1 <- predict(m1)
ggplot(dat, aes(x, y, color = group)) + geom_point() +
  geom_line(aes(y = m1), color = "black")
```

## Group as a factor but affects intercept only

```{r m2}
m2 <- lm(y ~ x + group, data = dat)
summary(m2)

dat$m2 <- predict(m2)
ggplot(dat, aes(x, y, color = group)) + geom_point() +
  geom_line(aes(y = m2), linetype = 2)
```

## Group as a factor but affects slope only

```{r m3}
m3 <- lm(y ~ x : group, data = dat)
summary(m3)

dat$m3 <- predict(m3)
ggplot(dat, aes(x, y, color = group)) + geom_point() +
  geom_line(aes(y = m3), linetype = 2)
```

## Group as a factor affecting both slope and intercept

```{r m4}
m4 <- lm(y ~ x * group, data = dat)
summary(m4)

dat$m4 <- predict(m4)
ggplot(dat, aes(x, y, color = group)) + geom_point() +
  geom_line(aes(y = m4), linetype = 2)
```

